### ISSUE TITLE
Processing .md file through pandoc = Latex Error

### ISSUE THREAD

**Issue by Hen-son** [LukasCBossert/hu-berlin-bundle#1]
Hi Lukas, 

very helpful Bundle. Had been using for several letters. Since the upgrade to Texlive 2020 the bundle is broken for me. Do you know if I am able to fix it on my side?

This is the .md file to be processed: 

```
---
documentclass: hu-berlin-letter
sender: hu-berlin-letter-example
subject: Short description
addressee:
- Alexander von Humboldt
- Unter den Linden 6
- 10099 Berlin
---
Thank you very much for your letter.
```

This is the Terminal command: 

`pandoc beispiel.md -o beispiel.pdf  --pdf-engine=lualatex --template hu-berlin-letter-template.latex`

This is the result: 
```
Error producing PDF.
! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.57 \opening{\usekomavar{opening}}

```

Processing it through Rmarkdown I get a more detailed error-Log (see below). Especially this seems to be troubling:  ` ! Missing $ inserted ` 

Do you have any idea where I could proceed investigating? Very basic understanding of those things here. 

Thanks for the great tool. 

Best
Henning

```
...
...
Foldmarks: yes
Head of first page
<hu-berlin-logo.pdf, id=1, 661.47125pt x 132.495pt>
File: hu-berlin-logo.pdf Graphic file (type pdf)
<use hu-berlin-logo.pdf>
Package luatex.def Info: hu-berlin-logo.pdf  used on input line 58.
(luatex.def)             Requested size: 412.56496pt x 82.63731pt.
File: hu-berlin-logo.pdf Graphic file (type pdf)
<use hu-berlin-logo.pdf>
Package luatex.def Info: hu-berlin-logo.pdf  used on input line 58.
(luatex.def)             Requested size: 412.56496pt x 82.63731pt.
Foot of first page
Address: No
Location field: yes
LaTeX Font Info:    Trying to load font information for U+mvs on input line 58.
(/usr/local/texlive/2020basic/texmf-dist/tex/latex/marvosym/umvs.fd)
Title: no
Subject: no
! Missing $ inserted.
<inserted text> 
$
l.58 \opening{\usekomavar{opening}}
                                 ```

**Comment by LukasCBossert** [comment]
Hi Henning,

thank you for the feedback - always nice to hear that someone is using this package.

Thank you very much for the bug report - I could find the issue

```
Class scrlttr2 Warning: Usage of deprecated command `\ifkomavarempty'.
(scrlttr2)              The command has been renamed to because of a
(scrlttr2)              recommendation of LaTeX3 team members.
(scrlttr2)              Please replace `\ifkomavarempty' by `\Ifkomavarempty' o
n input line 30.
```

This change must have happend with the latest update of the KOMAscripts.
It should also fix the error with Rmarkdown.

Fix is on its way to CTAN and probably available soon.

Best, Lukas

**Comment by Hen-son** [comment]
Hi Lukas,

Thank you for this quick answer! Very supportive. I did see this 
specific warning and already tried to alter the local file accordingly. 
Did not solve the issue, though (I think warnings are more or less 
ignorable?). But I will wait for your official fix and hope for the 
best.

Greetings,
Henning

**Comment by LukasCBossert** [comment]
hm - I tested the files and didnt get the error anymore. Maybe you can test with https://github.com/LukasCBossert/hu-berlin-bundle/blob/master/hu-berlin-letter.cls too?!

If there is still the error just reopen this issue.

**Comment by Hen-son** [comment]
Sorry, still problems here. Runs through fine with your hu-berlin-letter-example.lco file. But still the  `! Missing $ inserted.` error as soon as I point to my personalized .lco file (see below). Cannot see any meaningful differences between my modifications (see below) and your example. Do you have a clue? 


Best, Henning


```
\ProvidesFile{hu-berlin-letter-fueller.lco}
\setkomavar{fromname}
  [Wissenschaftlicher Mitarbeiter]
  {Dr. Henning Füller}
\setkomavar{fromemail}{henning.fueller@geo.hu-berlin.de}
\setkomavar{fromphone}{9315}
\setkomavar{fromfax}{6853}
\setkomavar{fromurl}{https://www.geographie.hu-berlin.de/de/Members/fueller_henning}
\setkomavar{backaddress}{HU Berlin\\
Unter den Linden 6\\
D-10099 Berlin}
\setkomavar{faculty}{%
Math.-Nat. Fakultät
}
\setkomavar{institute}{%
  \mbox{Geographisches Institut}
}
\setkomavar{institute.additional}{Here you can add more text.}
\setkomavar{institute.head}[Dekanin]{Prof. Dr. Maike Musterfrau}
\setkomavar{institute.head.mail}{maike.musterfrau@hu-berlin.de}
\setkomavar{local}{%
  Rudower Chaussee 16\\
  Raum 3'108 (Neubau)\\
  D-12489 Berlin}
\setkomavar{connections}{U Bahnhof Adlershof}
\setkomavar{accessibility}{Adlershof}
\setkomavar{signature}{%
  \usekomavar{institute.head} --
  \usekomavar{fromname}
}
%%
%% Copyright (C) 2019-2020
%%
%% End of file `hu-berlin-letter-fueller.lco'.
```

**Comment by LukasCBossert** [comment]
try to escape the underscore in the url
...henning\_fueller....

can’t test right now will do later

**Comment by LukasCBossert** [comment]
`henning\_fueller`

**Comment by Hen-son** [comment]
This did the trick! (Confusing as my file did work for several letters 
without this escaping, not sure why it suddenly became a trouble)

Thanks again. Happy to continue with well formatted official 
correspondence.

Best,
Henning

**Comment by LukasCBossert** [comment]
Happy to hear that it works now! 
Hope to hear from you again when there are more issues with the bundle, currently I am not using it so I need some feedback from others.

Best,
Lukas

**Comment by Hen-son** [comment]
Lieber Lukas,

Immer noch ein zufriedener Nutzer Deines Pandoc-Briefvorlage für die 
HU. Heute bin ich allerdings an eine Grenze gestossen bei dem Abfassen 
eines englischsprachigen Empfehlungsschreibens. Fakultät und Institut 
kann ich ganz einfach selbst ändern durch ein angepasstes .lco Datei. 
Aber die ganzen festen Überschriften in der rechten Spalte bleiben dann 
immer noch auf deutsch. Ich habe versucht, das in der Letter class 
option Datei zu ändern oder sogar sprachbasiert anzupassen aber bin 
leider nicht zum Ziel gekommen.

Ich habe immer die Fehlermeldung: ! Package scrbase Error: `\bank' 
already defined
(scrbase)                for language `ngerman'.

Vielleicht hast Du auf einen Blick eine Idee, woran das liegen könnte?

Ich hänge Dir für alle Fälle mal die veränderte .cls Datei an.

Herzlichen Gruß,
Henning





***

Dr. Henning Füller
Geographisches Institut
Humboldt-Universität zu Berlin

henning.fueller@geo.hu-berlin.de
http://hu.berlin/fueller

On 28 Apr 2020, at 21:02, Lukas C. Bossert wrote:

> Hi Henning,
>
> thank you for the feedback - always nice to hear that someone is using 
> this package.
>
> Thank you very much for the bug report - I could find the issue
>
> ```
> Class scrlttr2 Warning: Usage of deprecated command `\ifkomavarempty'.
> (scrlttr2)              The command has been renamed to because of a
> (scrlttr2)              recommendation of LaTeX3 team members.
> (scrlttr2)              Please replace `\ifkomavarempty' by 
> `\Ifkomavarempty' o
> n input line 30.
> ```
>
> This change must have happend with the latest update of the 
> KOMAscripts.
> It should also fix the error with Rmarkdown.
>
> Fix is on its way to CTAN and probably available soon.
>
> Best, Lukas
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LukasCBossert/hu-berlin-bundle/issues/1#issuecomment-620796499


%%
%% This is file `hu-berlin-letter.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% hu-berlin-bundle.dtx  (with options: `cls,letter')
%% ----------------------------------------------------------------
%% hu-berlin-bundle
%% Author:  Lukas C. Bossert
%% E-mail:  lukas@texografie.de
%% License: Released under the LaTeX Project Public License v1.3c or later
%% See:     http://www.latex-project.org/lppl.txt
%% Various parts my have a different licence,
%% please consider and respect them carefully.
%% ----------------------------------------------------------------
%%
\def\Version{2020/10/30 v1.0.8}
\NeedsTeXFormat{LaTeX2e}[2005/12/01]
\ProvidesClass{hu-berlin-letter}
  [\Version\ Humboldt-Universit"at zu Berlin - letter documentclass]
\ClassInfo{hu-berlin}{* * * hu-berlin * * *\MessageBreak
    Part of the hu-berlin Bundle }
\LoadClass[%
  fontsize=10pt,
  version=last,
  % visualize
]{scrlttr2}
\RequirePackage{hu-berlin-base}
\RequirePackage{scrlayer-scrpage}
\clearpairofpagestyles
\DeclareNewLayer[
 foreground,
 voffset=\useplength{firstheadvpos},
 hoffset=\useplength{firstheadhpos},
 width=\useplength{firstheadwidth},
 mode=picture,
 contents=\putUL{\raisebox{-\height}{\usekomavar{firsthead}}}
]{likefirstpage.head}
\AddLayersToPageStyle{scrheadings}{likefirstpage.head}
\DeclareNewLayer[
 foreground,
 align=r,
 voffset=\useplength{locvpos},
 hoffset=\paperwidth-\useplength{lochpos},
 width=\useplength{locwidth},
 height=\useplength{locheight},
 contents=\usekomavar{nextlocation},
 %pretocontents=\layercontentsmeasure% to show the position of the layer
]{likefirstpage.loc}
\AddLayersToPageStyle{scrheadings}{likefirstpage.head,likefirstpage.loc}
\newkomavar{nextlocation}
\setkomavar{nextlocation}{%
  \raggedright
  \fontsize{7}{8.5}\selectfont
  \pagemark
}
\RequirePackage{geometry}
\geometry{%
  a4paper
 ,left           =25mm
 ,bottom         =16mm
 ,foot           =4mm
 ,top            =77mm
 ,headheight     =15pt
 ,textwidth      =117mm
 ,marginparsep   =0mm
 ,marginparwidth =0mm
}
\renewcommand*{\raggedsignature}{\raggedright}
\raggedright
\def\stopletter{}
\let\enclold\encl
\renewcommand\encl[1]{\vskip0ptplus1filll\enclold{#1}}
\newkomavar{faculty}
\newkomafont{faculty}{\bfseries\fontsize{8.5}{10}\selectfont}
\newkomavar{institute}
\newkomafont{institute}{\fontsize{8.5}{10}\selectfont}
\newkomavar{institute.additional}
\newkomafont{institute.head}{\bfseries}
\newkomavar{institute.head}%
\newkomavar{institute.head.mail}%
\newkomavar{local}
\setkomavar*{local}{Sitz:}
\newkomavar{connections}
\setkomavar*{connections}{Verkehrsverbindungen:}
\newkomavar{officehours}
\setkomavar*{officehours}{Sprechzeiten:}
\newkomavar{accessibility}
\setkomavar*{accessibility}{{\large\reflectbox{\Wheelchair}} Eingang:}
\newkomavar{bank}
\setkomavar*{bank}{Bankverbindung:}
\setkomavar{bank}{Deutsche Bank PGK AG}
\newkomavar{IBAN}
\setkomavar{IBAN}{\mbox{IBAN DE95 1007 0848 0512 6206 01}}
\newkomavar{BIC}
\setkomavar{BIC}{BIC DEUTDEDB110}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Sprachabhängige Bezeichner deklarieren
\AtBeginDocument{%
%   DEUTSCH
\iflanguage{ngerman}{%
\providecaptionname{ngerman}{\bank}{Bankverbindung:}%
\providecaptionname{ngerman}{\connections}{öff. Verkehr}%
}{}
%   ENGLISCH
\iflanguage{english}{%
\providecaptionname{english}{\bank}{Account}%
\providecaptionname{english}{\connections}{Access}%
}{}
}%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\setkomavar{location}{%
  \raggedright
  \fontsize{7}{8.5}\selectfont
\begin{minipage}[t][64mm]{\useplength{locwidth}}
\Ifkomavarempty{faculty}
  {\hspace*{1em}}
  {\usekomafont{faculty}%
   \usekomavar{faculty}\\[1\baselineskip]}
\Ifkomavarempty{institute}
  {}
  {\usekomafont{institute}\usekomavar{institute}\\[1\baselineskip]}
\Ifkomavarempty{institute.additional}
  {}
  {\usekomavar{institute.additional}\\[1\baselineskip]}
\Ifkomavarempty{institute.head}
 {}
 {{\usekomafont{institute.head}%
  \usekomavar{institute.head}}\\%
 \usekomavar*{institute.head}}
 \end{minipage}
  \textbf{\usekomavar*{date}}\\
  \usekomavar{date}\par
\Ifkomavarempty{fromname}
 {}
 {\textbf{\usekomavar*{fromname}}\\
  \usekomavar{fromname}\par}
\Ifkomavarempty{myref}
 {}
 {\textbf{\usekomavar*{myref}}\\
  \usekomavar{myref}\par}
\Ifkomavarempty{yourref}
 {}
 {\textbf{\usekomavar*{yourref}}\\
  \usekomavar{yourref}\par}
\Ifkomavarempty{yourmail}
 {}
 {\textbf{\usekomavar*{yourmail}}\\
  \usekomavar{yourmail}\par}
\Ifkomavarempty{customer}
 {}
 {\textbf{\usekomavar*{customer}}\\
  \usekomavar{customer}\par}
\Ifkomavarempty{invoice}
 {}
 {\textbf{\usekomavar*{invoice}}\\
  \usekomavar{invoice}\par}
  \textbf{\usekomavar*{fromaddress}}\\
  \usekomavar{fromaddress}
  \Ifkomavarempty{fromphone}
    {\par}
    {\\\usekomavar*{fromphone}\usekomavar{fromphone}
     \Ifkomavarempty{fromfax}
    {\par}
    {\\}}
  \Ifkomavarempty{fromfax}
    {}
    {\usekomavar*{fromfax}\usekomavar{fromfax}\par}
\Ifkomavarempty{institute.head.mail}
  {}
  {\usekomavar{institute.head.mail}
  \Ifkomavarempty{fromemail}
  {\Ifkomavarempty{fromurl}
   {\par}
   {\\}}
  {\\}}
\Ifkomavarempty{fromemail}
  {}
  {\usekomavar{fromemail}
  \Ifkomavarempty{fromurl}
  {\par}
  {\\}}
\Ifkomavarempty{fromurl}
  {}
  {\usekomavar{fromurl}\par}
\Ifkomavarempty{local}
  {}
  {\textbf{\usekomavar*{local}}\\
  \usekomavar{local}\par}
\vfill
\Ifkomavarempty{connections}
  {}
  {\textbf{\usekomavar*{connections}}\\
  \usekomavar{connections}\par}
\Ifkomavarempty{officehours}
  {}
  {\textbf{\usekomavar*{officehours}}\\
  \usekomavar{officehours}\par}
\Ifkomavarempty{accessibility}
  {}
  {\textbf{\usekomavar*{accessibility}}\\
  \usekomavar{accessibility}\par}
\Ifkomavarempty{bank}
  {}
  {\textbf{\usekomavar*{bank}}\\
  \usekomavar{bank}\\
  \usekomavar{IBAN}\\
  \usekomavar{BIC}
  }
}
\KOMAoptions{%
   numericaldate =true
  ,refline       =nodate
  ,backaddress   =plain
  ,parskip       =half-
}
\removereffields
\setplength{refvpos}{110mm}
\setplength{refaftervskip}{0pt}
\setplength{toaddrhpos}{25mm}
\setplength{firstheadhpos}{\useplength{toaddrhpos}}
\setplength{lochpos}{15mm}
\setplength{locvpos}{\useplength{toaddrvpos}}
\addtoplength{locvpos}{.75\baselineskip}
\setplength{locwidth}{45mm}
\setplength{locheight}{232mm}
\setkomavar{firsthead}{%
\IfFileExists{hu-berlin-logo.pdf}
  {\includegraphics[width=145mm]{hu-berlin-logo.pdf}}
  {{\vspace*{2em}\hfil\scshape [humboldt-universität zu berlin]}}%
}
\setkomavar{backaddressseparator}{~\textbar~}
\setkomavar{fromphone}{0000}
\setkomavar*{fromphone}{Telefon +49 [30] 2093–}
\setkomavar{fromfax}{0000}
\setkomavar*{fromfax}{Telefax +49 [30] 2093–}
\setkomavar*{fromaddress}{Postanschrift:}
\setkomavar{fromaddress}{%
  Humboldt-Universität zu Berlin\\
  Unter den Linden 6\\
  D-10099 Berlin}
\setkomavar{backaddress}{%
  Humboldt-Universität zu Berlin\\
  UdL 6\\
  D-10099 Berlin}
\setkomavar*{date}{Datum:}
\setkomavar*{fromname}{Bearbeiter:}
\setkomavar*{myref}{Geschäftszeichen:}
\setkomavar*{enclseparator}{Anlage}
\setkomavar*{ccseparator}{Kopie an}
%%
%% Copyright (C) 2019-2020
%%
%% End of file `hu-berlin-letter.cls'.

**Comment by LukasCBossert** [comment]
Hi Henning,

vielen Dank für dein Feedback. 
Der Fokus auf Deutsch ist mir beim letzten Update auch schmerzlich aufgefallen. 
Ursprünglich hatte ich nicht gedacht, dass man eine andere Version als deutsch bzw. 'ngerman' bräuchte. Dein Fall zeigt aber, dass es notwendig ist.

An sich sollte es kein Problem sein, ich selbst bin bis zum 3.12. mit anderen Projekten beschäftigt aber spätestens dann sollte ich Zeit haben (vielleicht auch schon früher).

Ich habe für das Thema ein neues Issue aufgemacht: https://github.com/LukasCBossert/hu-berlin-bundle/issues/3

Wenn du magst, kannst du mir auch ein PullRequest schicken (falls du in der .dtx-Datei arbeiten kannst/willst).

Schöne Grüße
Lukas

**Comment by Hen-son** [comment]
Lieber Lukas,

Herzlichen Dank für die Auseinandersetzung mit dem Anliegen! Ich habe 
gestern länger probiert. Ich befürchte, es ist ein Sonderfall, der 
sich mit den Mitteln der KOMA-Klasse nicht lösen lässt. Dieses 
\renewcaption scheint jedenfalls nicht explizit für die Brief-Klasse in 
der KOMA-Dokumentation ausgeführt. Vielleicht hast Du aber eine Idee 
wie es doch gehen könnte. Es scheint im Grunde machbar, jedenfalls 
bieten andere Unis eine eine ähnliche Latex-Briefvorlage, die wohl 
entsprechend der Sprach-Einstellung die Briefvorlage anpasst. Habe das 
z.B. für die TU Braunschweig oder Dresden gefunden. Leider sind die 
Original-Dateien dort nicht öffentlich abrufbar, sondern nur die 
Dokumentationen:

https://tu-dresden.de/ressourcen/dateien/service/publizieren/cd/4_latex/dat/Handbuch_print.pdf?lang=de 
(siehe Seite 11)

Wie gesagt - freue mich über die Hilfe.

Herzlich,
Henning
